export const WEATHER_SET = 'WEATHER_SET';
export const INFO_SET = 'INFO_SET';
export const REFRESH_TIME = 'REFRESH_TIME';
export const SET_GREETINGS = 'SET_GREETINGS';
export const READINGLIST_SET = 'READINGLIST_SET';

export const LOGIN_CHECK = 'LOGIN_CHECK';
export const LOGIN_GET_DATA = 'LOGIN_GET_DATA';

export const INTERESTS_SUBMIT = 'INTERESTS_SUBMIT';

export const RECOMMENDATIONS_POPULATE = 'RECOMMENDATIONS_POPULATE';
export const RECOMMENDATIONS_CHANGE = 'RECOMMENDATIONS_CHANGE';
export const RECOMMENDATIONS_SUBMIT = 'RECOMMENDATIONS_SUBMIT';
export const RECOMMENDATIONS_RESET = 'RECOMMENDATIONS_RESET';